url: http://wangchen.info/refactoring-cheat-sheet
markdown: redcarpet 
pygments: true 
baseurl: /
relative_permalinks: false
title: Refactoring-Cheat-Sheet
description: Refactoring-Cheat-Sheet
exclude: ["README.md", "CNAME"]
